Repository unicef/inventory-hugo-theme, pull requests merged in 2021-12, with the labels that each got.

#38 Adjust UNICEF global link on mobile
  assets/css/style.css
  layouts/partials/navigation.html
Labels: T: bug

#43 :wrench: layouts: Use config-derived metadata for parent organization metadata
  layouts/partials/footer.html
  layouts/partials/navigation.html
Labels: T: improvement

#42 :lipstick: Add custom color to site title for matching logo color
  assets/css/style.css
  layouts/partials/head.html
  layouts/partials/navigation.html
Labels: T: improvement

#41 :memo: docs: Add a sample configuration for a Hugo site
  README.md
  sample_config.yaml
Labels: T: improvement, C: documentation
