Repository unicef/inventory-hugo-theme, pull requests merged in 2022-03, with the labels that each got.

#58 :lipstick: layouts(navigation): Use consistent color on all pages
  layouts/partials/navigation.html
Labels: T: bug

#44 :new: :lipstick: layouts: Add dpg-report layout (see unicef/coach#1)
  assets/css/style.css
  data/dpg_standards.yaml
  layouts/_default/dpg-report.html
  layouts/partials/dpg-report.html
  layouts/partials/head.html
Labels: ?: blocked, T: new change, C: design thinking

#70 Create table.html
  layouts/shortcodes/table.html
Labels: T: new change

#56 Added embed-pdf shortcode
  exampleSite/content/installation/configuration/_index.en.md
  exampleSite/content/installation/elements/_index.en.md
  exampleSite/static/pdfs/sample.pdf
  layouts/shortcodes/embed-pdf.html
Labels: T: new change

#68 Add condition to only show "RA Section" when there's content available
  layouts/partials/default.html
Labels: T: bug

#73 Make Table of Contents more appealing and responsive
  assets/css/style.css
Labels: T: improvement

#72 🐛 fix: Improved styling of highlight code blocks
  assets/css/style.css
  exampleSite/config.yaml
Labels: T: bug

#74 :recycle: layouts(dpg-report): Reuse download-pdf partial
  layouts/partials/dpg-report.html
Labels: T: improvement

#80 Removed Duplicate Home Link in Footer
  exampleSite/config.yaml
Labels: T: bug

#82 :bug: :memo: README: Fix link for example site config
  README.md
Labels: T: bug, C: documentation
