Repository unicef/inventory-hugo-theme, pull requests merged in 2022-04, with the labels that each got.

#86 :new: :memo: .github: Add contributing guidelines
  .github/CONTRIBUTING.md
  README.md
Labels: C: documentation, I: contributor experience, T: new change

#83 💄 fix: Added shortcodes for CAUTION and IMPORTANT admonition
  assets/css/style.css
  exampleSite/content/installation/elements/_index.en.md
  exampleSite/content/installation/elements/_index.fr.md
Labels: T: new change

#94 Highlight the background color of buttons while hovering.
  assets/css/style.css
  exampleSite/config.yaml
  layouts/partials/head.html
Labels: T: improvement
