Repository unicef/inventory-hugo-theme, pull requests merged in 2022-06, with the labels that each got.

#110 added edit-this-page btn
  assets/css/style.css
  assets/js/script.js
  exampleSite/config.yaml
  i18n/en.yaml
  i18n/fr.yaml
  layouts/partials/default.html
Labels: T: new change

#109 Fixes#107
  layouts/partials/cohorts.html
  layouts/partials/types.html
  layouts/profiles/list.html
  layouts/profiles/single.html
  layouts/shortcodes/embed-pdf.html
  layouts/team/list.html
Labels: T: improvement

#115 added author byline
  exampleSite/content/installation/customization/_index.en.md
  layouts/partials/default.html
Labels: T: new change

#116 changed colour variables
  exampleSite/config.yaml
Labels: T: improvement

#117 card UI improvement
  assets/css/style.css
Labels: T: improvement

#131 primary btn hover fix
  assets/css/style.css
Labels: T: bug

#132 Broken Link Fix
  README.md
Labels: T: bug

#134 :sparkles: layouts: Add redirect layout and docs (closes #69)
  exampleSite/config.yaml
  exampleSite/content/features/redirect.en.adoc
  i18n/en.yaml
  i18n/fr.yaml
  layouts/redirect/single.html
Labels: T: new change

#135 :memo: README: Add attribution note for Data Science & A.I. Toolkit
  README.md
Labels: T: improvement, C: documentation

#137 :new: :memo: Add contributing category & key stakeholders (closes #127)
  exampleSite/content/contributing/_index.en.md
  exampleSite/content/contributing/stakeholders.en.adoc
Labels: C: documentation, T: new change

#138 Used hugo in breadcrumb bar functionality instead of javascript
  assets/css/style.css
  layouts/partials/breadcrumb.html
Labels: T: improvement
