Repository unicef/inventory-hugo-theme, pull requests merged in 2022-07, with the labels that each got.

#141 Modified cohorts and types partials to make it uniform with the theme.
  layouts/partials/cohorts.html
  layouts/partials/types.html
Labels: T: bug

#148 :building_construction: exampleSite: Initialize new content structure (closes #89)
  README.md
  exampleSite/config.yaml
  exampleSite/content/about/_index.en.adoc
  exampleSite/content/about/_index.es.adoc
  exampleSite/content/billing-pricing/_index.en.md
  exampleSite/content/billing-pricing/_index.fr.md
  exampleSite/content/billing-pricing/bill/_index.en.md
  exampleSite/content/billing-pricing/bill/_index.fr.md
  exampleSite/content/billing-pricing/bill/img-1.jpg
  exampleSite/content/billing-pricing/manage/_index.en.md
  exampleSite/content/billing-pricing/manage/_index.fr.md
  exampleSite/content/billing-pricing/manage/img-1.jpg
  exampleSite/content/billing-pricing/ownership/_index.en.md
  exampleSite/content/billing-pricing/ownership/_index.fr.md
  exampleSite/content/billing-pricing/ownership/img-1.jpg
  exampleSite/content/billing-pricing/payment/_index.en.md
  exampleSite/content/billing-pricing/payment/_index.fr.md
  exampleSite/content/billing-pricing/payment/img-1.jpg
  exampleSite/content/billing-pricing/profile/_index.en.md
  exampleSite/content/billing-pricing/profile/_index.fr.md
  exampleSite/content/billing-pricing/profile/img-1.jpg
  exampleSite/content/install/_index.en.md
  exampleSite/content/install/_index.fr.md
  exampleSite/content/install/configuration/_index.en.md
  exampleSite/content/install/configuration/_index.fr.md
  exampleSite/content/install/customization/_index.en.md
  exampleSite/content/install/customization/_index.fr.md
  exampleSite/content/install/elements/_index.en.md
  exampleSite/content/install/elements/_index.fr.md
  exampleSite/content/install/elements/img-1.jpg
  exampleSite/content/install/install/_index.en.md
  exampleSite/content/install/install/_index.fr.md
  exampleSite/content/install/requirments/_index.en.md
  exampleSite/content/install/requirments/_index.fr.md
  exampleSite/content/install/requirments/hugo.jpg
  i18n/es.yaml
  i18n/fr.yaml
Labels: C: documentation, T: new change

#149 :building_construction: exampleSite: Document key features (closes #119)
  exampleSite/config.yaml
  exampleSite/content/about/lorem-ipsum.en.adoc
  exampleSite/content/features/_index.en.md
  exampleSite/content/features/_index.es.md
  exampleSite/content/features/_index.fr.md
  exampleSite/content/features/_template.en.adoc
  exampleSite/content/features/admonitions/_index.en.adoc
  exampleSite/content/features/author-byline/_index.en.adoc
  exampleSite/content/features/author-byline/byline-example.png
  exampleSite/content/features/brand-identity/_index.en.adoc
  exampleSite/content/features/code-highlighting/_index.en.adoc
  exampleSite/content/features/linux/_index.en.md
  exampleSite/content/features/linux/_index.fr.md
  exampleSite/content/features/linux/img-1.jpg
  exampleSite/content/features/mac/_index.en.md
  exampleSite/content/features/mac/_index.fr.md
  exampleSite/content/features/mac/img-1.jpg
  exampleSite/content/features/redirect.en.adoc
  exampleSite/content/features/redirect/_index.en.adoc
  exampleSite/content/features/routing/_index.en.md
  exampleSite/content/features/routing/_index.fr.md
  exampleSite/content/features/routing/img-1.jpg
  exampleSite/content/features/tab-tables/_index.en.adoc
  exampleSite/content/features/tab-tables/tab-2.jpg
  exampleSite/content/features/tab-tables/tab-3.jpg
  exampleSite/content/features/ubuntu/_index.en.md
  exampleSite/content/features/ubuntu/_index.fr.md
  exampleSite/content/features/ubuntu/img-1.jpg
  exampleSite/content/features/windows/_index.en.md
  exampleSite/content/features/windows/_index.fr.md
  exampleSite/content/features/windows/img-1.jpg
  exampleSite/content/install/configuration/_index.en.md
  exampleSite/content/install/configuration/_index.fr.md
  exampleSite/content/install/customization/_index.en.md
  exampleSite/content/install/customization/_index.fr.md
  exampleSite/content/install/elements/_index.en.md
  exampleSite/content/install/elements/_index.fr.md
  exampleSite/content/install/elements/img-1.jpg
  exampleSite/static/pdfs/sample.pdf
  layouts/partials/navigation.html
Labels: ?: blocked, C: documentation, T: new change
