Repository unicef/inventory-hugo-theme, pull requests merged in 2022-10, with the labels that each got.

#169 Added displaying Page Tags functionality
  assets/css/style.css
  exampleSite/content/about/lorem-ipsum.en.adoc
  exampleSite/content/contributing/stakeholders.en.adoc
  exampleSite/content/features/_template.en.adoc
  exampleSite/content/features/admonitions/_index.en.adoc
  exampleSite/content/features/author-byline/_index.en.adoc
  exampleSite/content/features/brand-identity/_index.en.adoc
  exampleSite/content/features/code-highlighting/_index.en.adoc
  exampleSite/content/features/redirect/_index.en.adoc
  exampleSite/content/features/tab-tables/_index.en.adoc
  layouts/partials/default.html
  layouts/partials/page-tags.html
Labels: T: new change

#177 :bug: theme.toml: Fix TOML syntax error
  theme.toml
Labels: T: bug

#178 :art: :lipstick: layouts(index): Reduce padding around index text
  assets/css/style.css
  layouts/index.html
Labels: T: improvement
